language: bash

sudo: required
services:
  - docker

env:
  global:
    - DOCKER_ENGINE_VERSION=1.12.6
    - DOCKER_COMPOSE_VERSION=1.9.0
    - INITIAL_ADMIN_USER=admin.user
    - INITIAL_ADMIN_PASSWORD_PLAIN=admin123
    - COMPOSE_FILES="-f site/docker-compose.yml"
    - JEKYLL_SOURCE="/site"

before_install:
 - sudo apt-get install apt-transport-https ca-certificates curl software-properties-common
 - sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
 - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
 - sudo apt-get update
 - sudo apt-key update
 - sudo apt-get install docker-ce
 - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
 - chmod +x docker-compose
 - sudo mv docker-compose /usr/local/bin
 - docker --version
 - docker-compose --version

script:
  - ifconfig
